src/Entity/Training.php
<?php

namespace App\Entity;

use App\Repository\TrainingRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TrainingRepository::class)]
class Training
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $epochs = null;

    #[ORM\Column]
    private ?int $batch_size = null;

    #[ORM\Column(length: 255)]
    private ?string $activation = null;

    #[ORM\Column(length: 255)]
    private ?string $optimizer = null;

    #[ORM\Column(length: 255)]
    private ?string $img_size = null;

    #[ORM\Column(type: Types::ARRAY)]
    private array $kernels = [];

    #[ORM\Column(nullable: true)]
    private ?array $result = null;

    #[ORM\ManyToOne(fetch: 'EAGER', inversedBy: 'trainings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Model $model = null;

    #[ORM\ManyToOne(fetch: 'EAGER', inversedBy: 'trainings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Dataset $dataset = null;

    #[ORM\ManyToOne(targetEntity: self::class)]
    private ?self $parent_training = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $startRun = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $endRun = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEpochs(): ?int
    {
        return $this->epochs;
    }

    public function setEpochs(int $epochs): static
    {
        $this->epochs = $epochs;

        return $this;
    }

    public function getBatchSize(): ?int
    {
        return $this->batch_size;
    }

    public function setBatchSize(int $batch_size): static
    {
        $this->batch_size = $batch_size;

        return $this;
    }

    public function getActivation(): ?string
    {
        return $this->activation;
    }

    public function setActivation(string $activation): static
    {
        $this->activation = $activation;

        return $this;
    }

    public function getOptimizer(): ?string
    {
        return $this->optimizer;
    }

    public function setOptimizer(string $optimizer): static
    {
        $this->optimizer = $optimizer;

        return $this;
    }

    public function getImgSize(): ?string
    {
        return $this->img_size;
    }

    public function setImgSize(string $img_size): static
    {
        $this->img_size = $img_size;

        return $this;
    }

    public function getKernels(): array
    {
        return $this->kernels;
    }

    public function setKernels(array $kernels): static
    {
        $this->kernels = $kernels;

        return $this;
    }

    public function getResult(): ?array
    {
        return $this->result;
    }

    public function setResult(?array $result): static
    {
        $this->result = $result;

        return $this;
    }

    public function getModel(): ?Model
    {
        return $this->model;
    }

    public function setModel(?Model $model): static
    {
        $this->model = $model;

        return $this;
    }

    public function getDataset(): ?Dataset
    {
        return $this->dataset;
    }

    public function setDataset(?Dataset $dataset): static
    {
        $this->dataset = $dataset;

        return $this;
    }

    public function getParentTraining(): ?self
    {
        return $this->parent_training;
    }

    public function setParentTraining(?self $parent_training): static
    {
        $this->parent_training = $parent_training;

        return $this;
    }

    public function getStartRun(): ?\DateTimeInterface
    {
        return $this->startRun;
    }

    public function setStartRun(?\DateTimeInterface $startRun): static
    {
        $this->startRun = $startRun;

        return $this;
    }

    public function getEndRun(): ?\DateTimeInterface
    {
        return $this->endRun;
    }

    public function setEndRun(?\DateTimeInterface $endRun): static
    {
        $this->endRun = $endRun;

        return $this;
    }
}

templates/neural_pilot/edit-trained.html.twig
{% extends 'base.html.twig' %}

{% block title %}details{% endblock %}

{% block body %}
    <h1 class="title">Details</h1>

    <div class="card-breadcrumb">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bc-el">
                <li class="breadcrumb-item"><a href="{{ path('neural_pilot_index') }}">Run models</a></li>
                <li class="breadcrumb-item"><a href="{{ path('neural_pilot_list') }}">Models</a></li>
                <li class="breadcrumb-item">Model edit</li>
            </ol>
        </nav>
    </div>

    <div class="mb-3">
        <div class="row">
            <div class="col-md-2">
                <a href="{{ path('neural_pilot_remove', {id: model.id}) }}" class="btn btn-danger">Remove</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-7">
            <form action="{{ path('neural_pilot_edit-created-model', {id: model.id}) }}" method="post"
                  enctype="multipart/form-data">

                <b>Model</b>
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="nameInput" name="nameInput" value="{{ model.name }}">
                    <label for="nameInput">Name</label>
                </div>

                {% if model.path %}
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="classNamesInput" name="classNamesInput"
                               value="{{ model.classNames }}">
                        <label for="classNamesInput">Class names (separate by ',')</label>
                    </div>
                {% endif %}

                <div class="form-floating mb-3">
            <textarea
                    class="form-control"
                    placeholder="Description…"
                    id="descriptionTextarea"
                    name="descriptionInput"
                    cols="10">{{ model.description }}</textarea>
                    <label for="descriptionTextarea">Description</label>
                </div>

                <button type="submit" class="btn btn-primary" name="submitEditModelInput">Save</button>
            </form>

            <hr>

            <form action="{{ path('neural_pilot_edit-created-model', {id: model.id}) }}" method="post"
                  enctype="multipart/form-data">
                <b>Training</b>
                <div class="form-floating mb-3">
                    <select class="form-select" aria-label="Default select example" name="datasetIdInput" required>
                        {% for dataset in datasets %}
                            {% if dataset == training.dataset %}
                                <option value="{{ dataset.id }}" selected>{{ dataset.name }}</option>
                            {% else %}
                                <option value="{{ dataset.id }}">{{ dataset.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>

                <div class="form-floating mb-3">
                    <input type="number" class="form-control" id="epochsInput" name="epochsInput"
                           value="{{ training.epochs }}" required>
                    <label for="epochsInput">Epochs</label>
                </div>

                <div class="form-floating mb-3">
                    <input type="number" class="form-control" id="batchSizeInput" name="batchSizeInput"
                           value="{{ training.batchSize }}" required>
                    <label for="batchSizeInput">Batch Size</label>
                </div>

                <div class="form-floating mb-3">
                    <select class="form-select" aria-label="Default select example" name="activationInput" required>
                        <option value="relu">relu</option>
                        <option value="sigmoid">sigmoid</option>
                        <option value="tanh">tanh</option>
                        <option value="elu">elu</option>
                    </select>
                </div>

                <div class="form-floating mb-3">
                    <select class="form-select" aria-label="Default select example" name="optimizerInput" required>
                        <option value="adam">adam</option>
                        <option value="adagrad">adagrad</option>
                        <option value="adadelta">adadelta</option>
                        <option value="adamax">adamax</option>
                        <option value="rmsprop">rmsprop</option>
                    </select>
                </div>

                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="imgSizeInput" name="imgSizeInput"
                           value="{{ training.imgSize }}" required>
                    <label for="imgSizeInput">Image Size (height, width)</label>
                </div>

                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="kernelsInput" name="kernelsInput"
                           value="{{ training.kernels|join(',') }}" required>
                    <label for="kernelsInput">Kernels</label>
                </div>

                <button type="submit" class="btn btn-primary" name="submitTrainAgainInput">Train Again</button>
            </form>

            {% if model.status == 3 %}
            <hr>

            <div class="card">
                <div class="card-header">
                    API
                </div>
                <div class="card-body">
                    <p class="card-text">
                        <b>Get Details about model</b><br>
                        <code>curl -X GET http://localhost:8000/api/model/details/{{ model.id }}</code><br>
                        <b>Run model</b><br>
                        <code>curl -X POST -F "itemInput=@/path/to/file.jpg" http://localhost:8000/api/model/run/{{ model.id }}</code>
                    </p>
                </div>
            </div>
            {% endif %}
        </div>

        <div class="col-md-4 offset-md-1">
            <br>
            {% if result %}
                <div class="card">
                    <div class="card-header">
                        Result
                    </div>
                    <div class="card-body">
                        <p class="card-text">
                            {% for res in result %}
                                {{ res }} <br>
                            {% endfor %}
                        </p>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/neural_pilot/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}details{% endblock %}

{% block body %}
    <h1 class="title">Details</h1>

    <div class="card-breadcrumb">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bc-el">
                <li class="breadcrumb-item"><a href="{{ path('neural_pilot_index') }}">Run models</a></li>
                <li class="breadcrumb-item"><a href="{{ path('neural_pilot_list') }}">Models</a></li>
                <li class="breadcrumb-item">Model edit</li>
            </ol>
        </nav>
    </div>

    <div class="mb-3">
        <div class="row">
            <div class="col-md-2">
                <a href="{{ path('neural_pilot_remove', {id: model.id}) }}" class="btn btn-danger">Remove</a>
            </div>
        </div>
    </div>

    <div class="col-md-7">
        <form action="{{ path('neural_pilot_edit-added-model', {id: model.id}) }}" method="post"
              enctype="multipart/form-data">
            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="nameInput" name="nameInput" value="{{ model.name }}">
                <label for="nameInput">Name</label>
            </div>

            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="classNamesInput" name="classNamesInput"
                       value="{{ model.classNames }}">
                <label for="classNamesInput">Class names (separate by ',')</label>
            </div>

            <div class="form-floating mb-3">
            <textarea
                    class="form-control"
                    placeholder="Description…"
                    id="descriptionTextarea"
                    name="descriptionInput"
                    cols="10">{{ model.description }}</textarea>
                <label for="descriptionTextarea">Description</label>
            </div>

            <button type="submit" class="btn btn-primary" name="submitInput">Save</button>
        </form>

        {% if model.status == 1 %}
            <hr>

            <div class="card">
                <div class="card-header">
                    API
                </div>
                <div class="card-body">
                    <p class="card-text">
                        <b>Get Details about model</b><br>
                        <code>curl -X GET http://localhost:8000/api/model/details/{{ model.id }}</code><br>
                        <b>Run model</b><br>
                        <code>curl -X POST -F "itemInput=@/path/to/file.jpg" http://localhost:8000/api/model/run/{{ model.id }}</code>
                    </p>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/neural_pilot/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}index{% endblock %}

{% block body %}
    <h1 class="title">ML Result</h1>

    <div class="row">
        <div class="col-md-6">
            <form action="{{ path('neural_pilot_index') }}" method="post" enctype="multipart/form-data">
                <div class="mb-3">
                    <select class="form-select" aria-label="Select model" name="modelInput" required>
                        <option value="" selected disabled>Select model</option>
                        {% for model in models %}
                            <option value="{{ model.id }}">{{ model.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <label for="formFile" class="form-label">Choose the item file</label>
                    <input class="form-control" type="file" id="formFile" name="itemInput" required>
                </div>
                <button type="submit" class="btn btn-primary" name="loadModel">Fire</button>
            </form>
        </div>
        <div class="col-md-3">
            <a href="{{ path('neural_pilot_list') }}" class="btn btn-success">too few models?</a>
        </div>
    </div>

    <div id="loading" style="display: none;">
        <p>Loading...</p>
    </div>

    {% if data %}
        <div class="col-md-6">
            <div class="card result">
                <div class="card-header">
                    Result
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ data }}</h5>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block javascripts %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const form = document.querySelector('form');
            const loadingDiv = document.getElementById('loading');

            form.addEventListener('submit', function () {
                loadingDiv.style.display = 'block';
            });
        });
    </script>
{% endblock %}

{% block stylesheets %}
    <style>
        #loading {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background-color: white;
            border: 1px solid #ccc;
            padding: 20px;
            z-index: 1000;
        }
    </style>
{% endblock %}

templates/neural_pilot/model-add.html.twig
{% extends 'base.html.twig' %}

{% block title %}add{% endblock %}

{% block body %}
    <h1 class="title">Add new model</h1>

    <div class="card-breadcrumb">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bc-el">
                <li class="breadcrumb-item"><a href="{{ path('neural_pilot_index') }}">Run models</a></li>
                <li class="breadcrumb-item"><a href="{{ path('neural_pilot_list') }}">Models</a></li>
                <li class="breadcrumb-item">Model add</li>
            </ol>
        </nav>
    </div>

    <form action="{{ path('neural_pilot_add') }}" method="post" enctype="multipart/form-data">
        <div class="form-floating mb-3">
            <input type="text" class="form-control" id="nameInput" name="nameInput" required>
            <label for="nameInput">Name</label>
        </div>

        <div class="form-floating mb-3">
            <input type="text" class="form-control" id="classNamesInput" name="classNamesInput">
            <label for="classNamesInput">Class names (separate by ',')</label>
        </div>

        <div class="form-floating mb-3">
            <textarea
                    class="form-control"
                    placeholder="Description…"
                    id="descriptionTextarea"
                    name="descriptionInput"></textarea>
            <label for="descriptionTextarea">Description</label>
        </div>

        <div class="mb-3">
            <label for="formFile" class="form-label">Choose the model file</label>
            <input class="form-control" type="file" id="formFile" name="fileInput" required>
        </div>

        <button type="submit" class="btn btn-primary" name="submitInput">Save</button>
    </form>

{% endblock %}

templates/neural_pilot/model-create.html.twig
{% extends 'base.html.twig' %}

{% block title %}create{% endblock %}

{% block body %}
    <h1 class="title">Create new model</h1>

    <div class="card-breadcrumb">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bc-el">
                <li class="breadcrumb-item"><a href="{{ path('neural_pilot_index') }}">Run models</a></li>
                <li class="breadcrumb-item"><a href="{{ path('neural_pilot_list') }}">Models</a></li>
                <li class="breadcrumb-item">Model create</li>
            </ol>
        </nav>
    </div>

    <form action="{{ path('neural_pilot_create_model') }}" method="post" enctype="multipart/form-data">
        <div class="form-floating mb-3">
            <select class="form-select" aria-label="Default select example" name="datasetIdInput" required>
                {% for dataset in datasets %}
                    <option value="{{ dataset.id }}">{{ dataset.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-floating mb-3">
            <input type="number" class="form-control" id="epochsInput" name="epochsInput" required>
            <label for="epochsInput">Epochs</label>
        </div>

        <div class="form-floating mb-3">
            <input type="number" class="form-control" id="batchSizeInput" name="batchSizeInput" required>
            <label for="batchSizeInput">Batch Size</label>
        </div>

        <div class="form-floating mb-3">
            <select class="form-select" aria-label="Default select example" name="activationInput" required>
                <option value="relu" selected>relu</option>
                <option value="sigmoid">sigmoid</option>
                <option value="tanh">tanh</option>
                <option value="elu">elu</option>
            </select>
        </div>

        <div class="form-floating mb-3">
            <select class="form-select" aria-label="Default select example" name="optimizerInput" required>
                <option value="adam" selected>adam</option>
                <option value="adagrad">adagrad</option>
                <option value="adadelta">adadelta</option>
                <option value="adamax">adamax</option>
                <option value="rmsprop">rmsprop</option>
            </select>
        </div>

        <div class="form-floating mb-3">
            <input type="text" class="form-control" id="imgSizeInput" name="imgSizeInput" required>
            <label for="imgSizeInput">Image Size (height, width)</label>
        </div>

        <div class="form-floating mb-3">
            <input type="text" class="form-control" id="kernelsInput" name="kernelsInput" required>
            <label for="kernelsInput">Kernels</label>
        </div>

        <button type="submit" class="btn btn-primary" name="submitInput">Train</button>
    </form>

{% endblock %}

templates/neural_pilot/model_list.html.twig
{% extends 'base.html.twig' %}

{% block title %}list{% endblock %}

{% block body %}
    <h1 class="title">Models</h1>

    <div class="card-breadcrumb">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bc-el">
                <li class="breadcrumb-item"><a href="{{ path('neural_pilot_index') }}">Run models</a></li>
                <li class="breadcrumb-item">Models</li>
            </ol>
        </nav>
    </div>

    <div class="row">
        <div class="col-md-1">
            <div class="dropdown">
                <button class="btn btn-success dropdown-toggle" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                    Model...
                </button>
                <ul class="dropdown-menu">
                    <li><a href="{{ path('neural_pilot_add') }}" class="dropdown-item">Add</a></li>
                    <li><a href="{{ path('neural_pilot_create_model') }}" class="dropdown-item">Create</a></li>
                </ul>
            </div>
        </div>
        <div class="col-md-1">
            <a href="{{ path('neural_pilot_list_dataset') }}" class="btn btn-info">Datasets</a>
        </div>
    </div>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Status</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for model in models %}
            <tr>
                <th scope="row">{{ model.id }}</th>
                <td>{{ model.name }}</td>
                <td>
                    {% if model.status == 1 %}
                        Added
                    {% elseif model.status == 2 %}
                        Training
                    {% elseif model.status == 3 %}
                        Created
                    {% elseif model.status == 4 %}
                        Error
                    {% elseif model.status == 5 %}
                        Cancelled
                    {% endif %}
                </td>
                <td>
                    {% if model.status == 1 %}
                        <a href="{{ path('neural_pilot_edit-added-model', {id: model.id}) }}" class="btn btn-primary">Details</a>
                    {% elseif model.status == 2 %}
                        <a href="{{ path('neural_pilot_cancel_training', {id: model.id}) }}" class="btn btn-warning">Cancel</a>
                    {% elseif model.status == 3 %}
                        <a href="{{ path('neural_pilot_edit-created-model', {id: model.id}) }}" class="btn btn-primary">Details</a>
                    {% elseif model.status == 4 %}
                        <a href="{{ path('neural_pilot_edit-created-model', {id: model.id}) }}" class="btn btn-danger">Details</a>
                    {% elseif model.status == 5 %}
                        <div class="btn-group">
                            <a href="{{ path('neural_pilot_train_again', {id: model.id}) }}" class="btn btn-info">Try
                                again</a>
                            <button type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                <span class="visually-hidden">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{ path('neural_pilot_edit-created-model', {id: model.id}) }}">Details</a>
                                <li><a class="dropdown-item" href="{{ path('neural_pilot_remove', {id: model.id}) }}">Remove</a>
                                </li>
                            </ul>
                        </div>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if not models %}
        <div class="row justify-content-center">
            <div class="col-md-1">
                <p>Empty list</p>
            </div>
        </div>
    {% endif %}

{% endblock %}